[package]
name = "tsadaash"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.43"
chrono-tz = "0.10.4"
domain = "0.11.1"
inquire = "0.9.2"
rusqlite = "0.38.0"
strum = "0.27.2"
strum_macros = "0.27.2"
